//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Project/Input/EtherDomesInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace EtherDomes.Input
{
    public partial class @EtherDomesInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @EtherDomesInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""EtherDomesInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""move-0001-0000-0000-000000000001"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CycleTarget"",
                    ""type"": ""Button"",
                    ""id"": ""target-0002-0000-0000-000000000002"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClearTarget"",
                    ""type"": ""Button"",
                    ""id"": ""clear-0003-0000-0000-000000000003"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability1"",
                    ""type"": ""Button"",
                    ""id"": ""abil1-0004-0000-0000-000000000004"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability2"",
                    ""type"": ""Button"",
                    ""id"": ""abil2-0005-0000-0000-000000000005"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability3"",
                    ""type"": ""Button"",
                    ""id"": ""abil3-0006-0000-0000-000000000006"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability4"",
                    ""type"": ""Button"",
                    ""id"": ""abil4-0007-0000-0000-000000000007"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability5"",
                    ""type"": ""Button"",
                    ""id"": ""abil5-0008-0000-0000-000000000008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability6"",
                    ""type"": ""Button"",
                    ""id"": ""abil6-0009-0000-0000-000000000009"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability7"",
                    ""type"": ""Button"",
                    ""id"": ""abil7-0010-0000-0000-000000000010"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability8"",
                    ""type"": ""Button"",
                    ""id"": ""abil8-0011-0000-0000-000000000011"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability9"",
                    ""type"": ""Button"",
                    ""id"": ""abil9-0012-0000-0000-000000000012"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""wasd-bind-0001-0000-000000000001"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""wasd-up01-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""wasd-down-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""wasd-left-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""wasd-rght-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""gpad-move-0001-0000-000000000001"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""tab-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CycleTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""gpad-targ-0001-0000-000000000001"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CycleTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""esc-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ClearTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""gpad-clr0-0001-0000-000000000001"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ClearTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key1-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key2-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key3-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key4-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key5-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key6-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key7-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key8-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""key9-bind-0001-0000-000000000001"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Ability9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_CycleTarget = m_Player.FindAction("CycleTarget", throwIfNotFound: true);
            m_Player_ClearTarget = m_Player.FindAction("ClearTarget", throwIfNotFound: true);
            m_Player_Ability1 = m_Player.FindAction("Ability1", throwIfNotFound: true);
            m_Player_Ability2 = m_Player.FindAction("Ability2", throwIfNotFound: true);
            m_Player_Ability3 = m_Player.FindAction("Ability3", throwIfNotFound: true);
            m_Player_Ability4 = m_Player.FindAction("Ability4", throwIfNotFound: true);
            m_Player_Ability5 = m_Player.FindAction("Ability5", throwIfNotFound: true);
            m_Player_Ability6 = m_Player.FindAction("Ability6", throwIfNotFound: true);
            m_Player_Ability7 = m_Player.FindAction("Ability7", throwIfNotFound: true);
            m_Player_Ability8 = m_Player.FindAction("Ability8", throwIfNotFound: true);
            m_Player_Ability9 = m_Player.FindAction("Ability9", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_CycleTarget;
        private readonly InputAction m_Player_ClearTarget;
        private readonly InputAction m_Player_Ability1;
        private readonly InputAction m_Player_Ability2;
        private readonly InputAction m_Player_Ability3;
        private readonly InputAction m_Player_Ability4;
        private readonly InputAction m_Player_Ability5;
        private readonly InputAction m_Player_Ability6;
        private readonly InputAction m_Player_Ability7;
        private readonly InputAction m_Player_Ability8;
        private readonly InputAction m_Player_Ability9;
        public struct PlayerActions
        {
            private @EtherDomesInput m_Wrapper;
            public PlayerActions(@EtherDomesInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @CycleTarget => m_Wrapper.m_Player_CycleTarget;
            public InputAction @ClearTarget => m_Wrapper.m_Player_ClearTarget;
            public InputAction @Ability1 => m_Wrapper.m_Player_Ability1;
            public InputAction @Ability2 => m_Wrapper.m_Player_Ability2;
            public InputAction @Ability3 => m_Wrapper.m_Player_Ability3;
            public InputAction @Ability4 => m_Wrapper.m_Player_Ability4;
            public InputAction @Ability5 => m_Wrapper.m_Player_Ability5;
            public InputAction @Ability6 => m_Wrapper.m_Player_Ability6;
            public InputAction @Ability7 => m_Wrapper.m_Player_Ability7;
            public InputAction @Ability8 => m_Wrapper.m_Player_Ability8;
            public InputAction @Ability9 => m_Wrapper.m_Player_Ability9;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @CycleTarget.started += instance.OnCycleTarget;
                @CycleTarget.performed += instance.OnCycleTarget;
                @CycleTarget.canceled += instance.OnCycleTarget;
                @ClearTarget.started += instance.OnClearTarget;
                @ClearTarget.performed += instance.OnClearTarget;
                @ClearTarget.canceled += instance.OnClearTarget;
                @Ability1.started += instance.OnAbility1;
                @Ability1.performed += instance.OnAbility1;
                @Ability1.canceled += instance.OnAbility1;
                @Ability2.started += instance.OnAbility2;
                @Ability2.performed += instance.OnAbility2;
                @Ability2.canceled += instance.OnAbility2;
                @Ability3.started += instance.OnAbility3;
                @Ability3.performed += instance.OnAbility3;
                @Ability3.canceled += instance.OnAbility3;
                @Ability4.started += instance.OnAbility4;
                @Ability4.performed += instance.OnAbility4;
                @Ability4.canceled += instance.OnAbility4;
                @Ability5.started += instance.OnAbility5;
                @Ability5.performed += instance.OnAbility5;
                @Ability5.canceled += instance.OnAbility5;
                @Ability6.started += instance.OnAbility6;
                @Ability6.performed += instance.OnAbility6;
                @Ability6.canceled += instance.OnAbility6;
                @Ability7.started += instance.OnAbility7;
                @Ability7.performed += instance.OnAbility7;
                @Ability7.canceled += instance.OnAbility7;
                @Ability8.started += instance.OnAbility8;
                @Ability8.performed += instance.OnAbility8;
                @Ability8.canceled += instance.OnAbility8;
                @Ability9.started += instance.OnAbility9;
                @Ability9.performed += instance.OnAbility9;
                @Ability9.canceled += instance.OnAbility9;
            }

            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                {
                    @Move.started -= instance.OnMove;
                    @Move.performed -= instance.OnMove;
                    @Move.canceled -= instance.OnMove;
                    @CycleTarget.started -= instance.OnCycleTarget;
                    @CycleTarget.performed -= instance.OnCycleTarget;
                    @CycleTarget.canceled -= instance.OnCycleTarget;
                    @ClearTarget.started -= instance.OnClearTarget;
                    @ClearTarget.performed -= instance.OnClearTarget;
                    @ClearTarget.canceled -= instance.OnClearTarget;
                    @Ability1.started -= instance.OnAbility1;
                    @Ability1.performed -= instance.OnAbility1;
                    @Ability1.canceled -= instance.OnAbility1;
                    @Ability2.started -= instance.OnAbility2;
                    @Ability2.performed -= instance.OnAbility2;
                    @Ability2.canceled -= instance.OnAbility2;
                    @Ability3.started -= instance.OnAbility3;
                    @Ability3.performed -= instance.OnAbility3;
                    @Ability3.canceled -= instance.OnAbility3;
                    @Ability4.started -= instance.OnAbility4;
                    @Ability4.performed -= instance.OnAbility4;
                    @Ability4.canceled -= instance.OnAbility4;
                    @Ability5.started -= instance.OnAbility5;
                    @Ability5.performed -= instance.OnAbility5;
                    @Ability5.canceled -= instance.OnAbility5;
                    @Ability6.started -= instance.OnAbility6;
                    @Ability6.performed -= instance.OnAbility6;
                    @Ability6.canceled -= instance.OnAbility6;
                    @Ability7.started -= instance.OnAbility7;
                    @Ability7.performed -= instance.OnAbility7;
                    @Ability7.canceled -= instance.OnAbility7;
                    @Ability8.started -= instance.OnAbility8;
                    @Ability8.performed -= instance.OnAbility8;
                    @Ability8.canceled -= instance.OnAbility8;
                    @Ability9.started -= instance.OnAbility9;
                    @Ability9.performed -= instance.OnAbility9;
                    @Ability9.canceled -= instance.OnAbility9;
                }
            }

            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    RemoveCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerActions @Player => new PlayerActions(this);
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnCycleTarget(InputAction.CallbackContext context);
            void OnClearTarget(InputAction.CallbackContext context);
            void OnAbility1(InputAction.CallbackContext context);
            void OnAbility2(InputAction.CallbackContext context);
            void OnAbility3(InputAction.CallbackContext context);
            void OnAbility4(InputAction.CallbackContext context);
            void OnAbility5(InputAction.CallbackContext context);
            void OnAbility6(InputAction.CallbackContext context);
            void OnAbility7(InputAction.CallbackContext context);
            void OnAbility8(InputAction.CallbackContext context);
            void OnAbility9(InputAction.CallbackContext context);
        }

        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
    }
}
