namespace EtherDomes.Data
{
    /// <summary>
    /// Character class types available in the game.
    /// </summary>
    public enum CharacterClass
    {
        Warrior,     // Tank, DPS
        Mage,        // DPS
        Priest,      // Healer
        Paladin,     // Tank, Healer, DPS
        Rogue,       // DPS (Assassination, Combat) - Requirements 5.1
        Hunter,      // DPS (BeastMastery, Marksmanship) - Requirements 6.1
        Warlock,     // DPS (Affliction, Destruction) - Requirements 7.1
        DeathKnight  // Tank, DPS (Blood, Frost) - Requirements 8.1
    }

    /// <summary>
    /// Specializations for each class.
    /// </summary>
    public enum Specialization
    {
        // Warrior
        Protection = 0,    // Tank
        Arms = 1,          // DPS
        
        // Mage
        Fire = 10,         // DPS
        Frost = 11,        // DPS
        
        // Priest
        Holy = 20,         // Healer
        Shadow = 21,       // DPS
        
        // Paladin
        ProtectionPaladin = 30, // Tank
        HolyPaladin = 31,       // Healer
        Retribution = 32,       // DPS
        
        // Rogue (Requirements 5.1)
        Assassination = 40,     // DPS - DoT/Poison focused
        Combat = 41,            // DPS - Sustained damage
        
        // Hunter (Requirements 6.1)
        BeastMastery = 50,      // DPS - Pet focused
        Marksmanship = 51,      // DPS - Ranged damage focused
        
        // Warlock (Requirements 7.1)
        Affliction = 60,        // DPS - DoT focused
        Destruction = 61,       // DPS - Direct damage focused
        
        // Death Knight (Requirements 8.1)
        Blood = 70,             // Tank - Self-healing focused
        FrostDK = 71            // DPS - Dual-wield or two-handed
    }

    /// <summary>
    /// Item rarity levels with associated drop rates.
    /// </summary>
    public enum ItemRarity
    {
        Common,     // 70%
        Uncommon,   // 20%
        Rare,       // 7%
        Epic,       // 2.5%
        Legendary   // 0.5%
    }

    /// <summary>
    /// Types of items.
    /// </summary>
    public enum ItemType
    {
        Equipment,
        Consumable,
        Material,
        Quest,
        Currency
    }

    /// <summary>
    /// Equipment slots on a character.
    /// </summary>
    public enum EquipmentSlot
    {
        Head,
        Shoulders,
        Chest,
        Hands,
        Legs,
        Feet,
        MainHand,
        OffHand,
        Trinket1,
        Trinket2
    }


    /// <summary>
    /// Types of abilities in the game.
    /// </summary>
    public enum AbilityType
    {
        Damage,
        Healing,
        Buff,
        Debuff,
        Taunt,
        Utility
    }

    /// <summary>
    /// Types of damage that can be dealt.
    /// </summary>
    public enum DamageType
    {
        Physical,
        Fire,
        Frost,
        Holy,
        Shadow,
        Nature
    }

    /// <summary>
    /// Target types for the targeting system.
    /// </summary>
    public enum TargetType
    {
        Enemy,
        Friendly,
        Neutral
    }

    /// <summary>
    /// World regions with level ranges.
    /// </summary>
    public enum RegionId
    {
        Roca,      // Levels 1-15
        Bosque,    // Levels 15-30
        Nieve,     // Levels 30-40
        Pantano,   // Levels 40-50
        Ciudadela  // Levels 50-60
    }

    /// <summary>
    /// Dungeon sizes.
    /// </summary>
    public enum DungeonSize
    {
        Small, // 3 bosses
        Large  // 5 bosses
    }

    /// <summary>
    /// Boss encounter phases.
    /// </summary>
    public enum BossPhase
    {
        Phase1,  // 100% - 75%
        Phase2,  // 75% - 50%
        Phase3,  // 50% - 25%
        Phase4   // 25% - 0%
    }

    /// <summary>
    /// Loot distribution modes.
    /// </summary>
    public enum LootDistributionMode
    {
        RoundRobin,
        NeedGreed,
        MasterLooter
    }

    /// <summary>
    /// Connection approval error codes.
    /// </summary>
    public enum ApprovalErrorCode
    {
        None = 0,
        InvalidDataFormat = 1,
        CorruptedData = 2,
        StatsOutOfRange = 3,
        ValidationTimeout = 4,
        EncryptionFailure = 5,
        ServerFull = 6
    }

    /// <summary>
    /// Secondary resource types for class-specific mechanics.
    /// </summary>
    public enum SecondaryResourceType
    {
        None,       // Mage, Priest (MVP) - use Mana only
        Rage,       // Warrior - generated by dealing/receiving damage
        HolyPower,  // Paladin - generated by specific abilities
        Energy,     // Rogue - regenerates 10/s, 100 max (Requirements 5.2)
        Focus,      // Hunter - regenerates 5/s, 100 max (Requirements 6.2)
        ComboPoints // Rogue - generated by attacks, 5 max (Requirements 5.3)
    }

    /// <summary>
    /// Dungeon difficulty tiers.
    /// </summary>
    public enum DungeonDifficulty
    {
        Normal,
        Heroic,
        Mythic
    }

    /// <summary>
    /// Types of buff/debuff effects.
    /// </summary>
    public enum EffectType
    {
        Buff,       // Positive stat modification
        Debuff,     // Negative stat modification
        DoT,        // Damage over Time
        HoT,        // Healing over Time
        Slow,       // Movement speed reduction
        Stun,       // Prevents all actions
        Fear,       // Random movement
        Root        // Prevents movement only
    }

    /// <summary>
    /// Types of pets in the game.
    /// </summary>
    public enum PetType
    {
        Beast,      // Hunter pets
        Demon,      // Warlock generic demon
        Voidwalker, // Warlock tank pet
        Imp         // Warlock damage pet
    }

    /// <summary>
    /// States a pet can be in.
    /// </summary>
    public enum PetState
    {
        Following,  // Following the owner
        Attacking,  // Attacking a target
        Dead,       // Pet has died
        Dismissed   // Pet has been dismissed
    }

    /// <summary>
    /// Types of crowd control effects.
    /// Used for diminishing returns tracking.
    /// Requirements: 11.1, 11.2, 11.3, 11.6
    /// </summary>
    public enum CCType
    {
        None,       // No CC effect
        Slow,       // Movement speed reduction (Requirements 11.1)
        Stun,       // Prevents all actions (Requirements 11.2)
        Fear,       // Random movement (Requirements 11.3)
        Root        // Prevents movement only
    }
}
