using System;
using System.Collections.Generic;
using EtherDomes.Data;
using UnityEngine;

namespace EtherDomes.Combat
{
    /// <summary>
    /// Manages secondary resources for classes.
    /// 
    /// Resource Types:
    /// - Rage (Warrior): Generated by dealing/receiving damage, decays out of combat
    /// - Holy Power (Paladin): Generated by specific abilities, does not decay
    /// 
    /// Requirements: 9.3
    /// </summary>
    public class SecondaryResourceSystem : MonoBehaviour, ISecondaryResourceSystem
    {
        public const float RAGE_MAX = 100f;
        public const float RAGE_DECAY_RATE = 2f;        // Per second out of combat
        public const float RAGE_PER_DAMAGE_DEALT = 5f;  // Per hit
        public const float RAGE_PER_DAMAGE_TAKEN = 3f;  // Per hit received
        
        public const float HOLY_POWER_MAX = 5f;         // 5 points max
        public const float HOLY_POWER_PER_ABILITY = 1f; // Per generator ability

        private readonly Dictionary<ulong, ResourceState> _playerResources = new();

        public event Action<ulong, float, float> OnResourceChanged;

        public void RegisterResource(ulong playerId, SecondaryResourceType resourceType, float maxValue)
        {
            if (resourceType == SecondaryResourceType.None)
            {
                _playerResources.Remove(playerId);
                return;
            }

            float max = maxValue > 0 ? maxValue : GetDefaultMax(resourceType);
            
            _playerResources[playerId] = new ResourceState
            {
                ResourceType = resourceType,
                CurrentValue = 0,
                MaxValue = max
            };

            Debug.Log($"[SecondaryResource] Registered {resourceType} for player {playerId} (Max: {max})");
        }

        public void AddResource(ulong playerId, float amount)
        {
            if (!_playerResources.TryGetValue(playerId, out var state))
                return;

            if (amount <= 0)
                return;

            float oldValue = state.CurrentValue;
            state.CurrentValue = Mathf.Min(state.CurrentValue + amount, state.MaxValue);

            if (state.CurrentValue != oldValue)
            {
                OnResourceChanged?.Invoke(playerId, state.CurrentValue, state.MaxValue);
                Debug.Log($"[SecondaryResource] Player {playerId}: +{amount} {state.ResourceType} " +
                          $"({state.CurrentValue}/{state.MaxValue})");
            }
        }

        public bool TrySpendResource(ulong playerId, float amount)
        {
            if (!_playerResources.TryGetValue(playerId, out var state))
                return false;

            if (amount <= 0)
                return true;

            if (state.CurrentValue < amount)
                return false;

            state.CurrentValue -= amount;
            OnResourceChanged?.Invoke(playerId, state.CurrentValue, state.MaxValue);
            
            Debug.Log($"[SecondaryResource] Player {playerId}: -{amount} {state.ResourceType} " +
                      $"({state.CurrentValue}/{state.MaxValue})");
            
            return true;
        }

        public float GetResource(ulong playerId)
        {
            return _playerResources.TryGetValue(playerId, out var state) ? state.CurrentValue : 0;
        }

        public float GetMaxResource(ulong playerId)
        {
            return _playerResources.TryGetValue(playerId, out var state) ? state.MaxValue : 0;
        }

        public SecondaryResourceType GetResourceType(ulong playerId)
        {
            return _playerResources.TryGetValue(playerId, out var state) 
                ? state.ResourceType 
                : SecondaryResourceType.None;
        }

        public void ApplyDecay(ulong playerId, float deltaTime, bool inCombat)
        {
            if (!_playerResources.TryGetValue(playerId, out var state))
                return;

            // Only Rage decays, and only out of combat
            if (state.ResourceType != SecondaryResourceType.Rage)
                return;

            if (inCombat)
                return;

            if (state.CurrentValue <= 0)
                return;

            float decay = RAGE_DECAY_RATE * deltaTime;
            float oldValue = state.CurrentValue;
            state.CurrentValue = Mathf.Max(0, state.CurrentValue - decay);

            if (state.CurrentValue != oldValue)
            {
                OnResourceChanged?.Invoke(playerId, state.CurrentValue, state.MaxValue);
            }
        }

        /// <summary>
        /// Generate rage from dealing damage.
        /// </summary>
        public void GenerateRageFromDamageDealt(ulong playerId, float damageAmount)
        {
            if (!_playerResources.TryGetValue(playerId, out var state))
                return;

            if (state.ResourceType != SecondaryResourceType.Rage)
                return;

            AddResource(playerId, RAGE_PER_DAMAGE_DEALT);
        }

        /// <summary>
        /// Generate rage from taking damage.
        /// </summary>
        public void GenerateRageFromDamageTaken(ulong playerId, float damageAmount)
        {
            if (!_playerResources.TryGetValue(playerId, out var state))
                return;

            if (state.ResourceType != SecondaryResourceType.Rage)
                return;

            AddResource(playerId, RAGE_PER_DAMAGE_TAKEN);
        }

        /// <summary>
        /// Generate holy power from ability use.
        /// </summary>
        public void GenerateHolyPower(ulong playerId, float amount = 1f)
        {
            if (!_playerResources.TryGetValue(playerId, out var state))
                return;

            if (state.ResourceType != SecondaryResourceType.HolyPower)
                return;

            AddResource(playerId, amount);
        }

        /// <summary>
        /// Get the default max value for a resource type.
        /// </summary>
        public static float GetDefaultMax(SecondaryResourceType resourceType)
        {
            return resourceType switch
            {
                SecondaryResourceType.Rage => RAGE_MAX,
                SecondaryResourceType.HolyPower => HOLY_POWER_MAX,
                _ => 0
            };
        }

        /// <summary>
        /// Get the resource type for a character class.
        /// </summary>
        public static SecondaryResourceType GetResourceTypeForClass(CharacterClass characterClass)
        {
            return characterClass switch
            {
                CharacterClass.Warrior => SecondaryResourceType.Rage,
                CharacterClass.Paladin => SecondaryResourceType.HolyPower,
                CharacterClass.Mage => SecondaryResourceType.None,
                CharacterClass.Priest => SecondaryResourceType.None,
                _ => SecondaryResourceType.None
            };
        }

        /// <summary>
        /// Check if a resource type decays out of combat.
        /// </summary>
        public static bool DoesResourceDecay(SecondaryResourceType resourceType)
        {
            return resourceType == SecondaryResourceType.Rage;
        }

        /// <summary>
        /// Clear resource for a player.
        /// </summary>
        public void ClearResource(ulong playerId)
        {
            _playerResources.Remove(playerId);
        }

        /// <summary>
        /// Clear all resources.
        /// </summary>
        public void ClearAll()
        {
            _playerResources.Clear();
        }

        private class ResourceState
        {
            public SecondaryResourceType ResourceType;
            public float CurrentValue;
            public float MaxValue;
        }
    }
}
